### ISSUE TITLE
Insight2 cannot configure

### ISSUE THREAD

**Issue by wanglinxiao** [CshlSiepelLab/FitCons2#1]
I tried to configure Insight2, but I encountered an error that indicated a file could not be downloaded. And it seems to indicate that I did not have access permission, so I wonder how to solve it.

Mon Jul  1 10:13:01 CST 2024 Configuring Insight2 database.
Mon Jul  1 10:13:01 CST 2024	 Retrieving database file Insight2DB.tar from http://compgen.cshl.edu/~bgulko/research/Insight2/db/FitCons2/Insight2DB.tar .
wget: /picb/bigdata/project/wanglinxiao/anaconda3/lib/libuuid.so.1: no version information available (required by wget)
--2024-07-01 10:13:01--  http://compgen.cshl.edu/~bgulko/research/Insight2/db/FitCons2/Insight2DB.tar
Resolving compgen.cshl.edu (compgen.cshl.edu)... 143.48.220.190
Connecting to compgen.cshl.edu (compgen.cshl.edu)|143.48.220.190|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-07-01 10:13:02 ERROR 403: Forbidden.

Mon Jul  1 10:13:02 CST 2024	 Did not find database in Insight2DB.tar - build failed. Exiting.

**Comment by bgulko** [comment]
Thank you, I wrote this software and have confirmed that the directory is not presently publically available. While I wrote this software around 2015, I do not think it is actively maintained, however, I believe can offer this file directly. 

Please contact me via direct message or email, and I'll find a copy and make it available, if possible. This message should also go to the lab administrator to find a new location for this file. If not, I'll look for a more persistent home. Again, thanks for the note! --Brad

**Comment by wanglinxiao** [comment]
> Thank you, I wrote this software and have confirmed that the directory is not presently publically available. While I wrote this software around 2015, I do not think it is actively maintained, however, I believe can offer this file directly.
> 
> Please contact me via direct message or email, and I'll find a copy and make it available, if possible. This message should also go to the lab administrator to find a new location for this file. If not, I'll look for a more persistent home. Again, thanks for the note! --Brad

Thanks, Brad. But I don't know how to contact you(email or message), so I will leave my email address and look forward to your reply. My email: wanglinxiao2020@sinh.ac.cn

**Comment by bgulko** [comment]
I think GitHub used to have a private direct messaging capacity, but it looks like it does not now. My apologies!

I will send email to your address, so you will have my email as well. I provided the archive from my own backups to the SiepelLab, and they updated the link. I believe the database link is now (2024-Jul) available at:
 
http://compgen.cshl.edu/Insight2/db/FitCons2/Insight2DB.tar

--Brad
